"""
ET AI Concierge — Agentic LLM Service (Gemini-powered)
=========================================================
This is the true brain of the AI concierge. Unlike a simple chatbot,
this service:
1. Injects the FULL user profile into the system prompt so Gemini KNOWS
   who it is talking to (age, experience, goals, risk tolerance, etc.)
2. Passes the FULL conversation history so the bot remembers context
3. Includes page context (what page/article the user is on) so it can
   answer questions about what they're currently reading
4. Returns a structured JSON with:
   - 'answer': the actual reply to the user
   - 'cross_sell': a single PERSONALIZED ET service pitch generated by the LLM
     specific to THIS user's profile + THIS message + THIS context
"""

import os
import json
import logging
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeoutError
from typing import List, Dict, Any, Optional

from src.services.gemini_client import get_gemini_model
from src.database.connection import SessionLocal
from src.database.models import IPO

logger = logging.getLogger(__name__)

# ── Available ET services catalogue (real product data) ──────────────────────
ET_SERVICES_CATALOGUE = """
AVAILABLE ET SERVICES (use ONLY these, pick the MOST RELEVANT one):
1. ET Prime - Premium subscription ₹999/year or ₹99/month
   - Covers: Stock analysis, IPO ratings, Mutual fund reports, Business news, CEO interviews
   - Best for: Regular investors, professionals, business owners

2. ET Markets Data Terminal - ₹499/month  
   - Covers: Real-time NSE/BSE data, F&O chain, screeners, live charts, technical indicators
   - Best for: Active traders, day traders, F&O players

3. ET Masterclass: Stock Market Mastery 2026 - ₹1499
   - Covers: Stock picking, portfolio building, reading financials, technical analysis
   - Best for: Beginners to intermediate investors who want to learn

4. ET Masterclass: F&O Trading Strategies - ₹2499
   - Covers: Options strategies, hedging, income from F&O, Greeks
   - Best for: Experienced traders wanting to trade derivatives

5. ET Masterclass: Personal Finance for the 30s - ₹999
   - Covers: SIP strategy, tax planning, insurance, emergency fund, home loan
   - Best for: Young professionals aged 28-40

6. ET Masterclass: Retirement Planning Made Simple - ₹1299
   - Covers: Corpus calculation, senior citizen investments, annuities, pension
   - Best for: Age 40+ planning for retirement

7. ET Prime Tax Saving Bundle - ₹299 (FY26 special)
   - Covers: 80C guide, ELSS picks, NPS, tax harvesting strategies
   - Best for: Professionals wanting to save more in taxes

8. ET Markets IPO Tracker (in ET Prime) - FREE with ET Prime
   - Covers: Live GMP, allotment status, subscription numbers, expert ratings
   - Best for: IPO investors

9. ET Wealth Management Newsletter - ₹49/month
   - Covers: Weekly curated stock picks, portfolio review, market outlook
   - Best for: Passive investors wanting curated guidance
"""

def _build_system_prompt(user_profile: Optional[Dict] = None, page_context: Optional[str] = None) -> str:
    """Build a rich, profile-aware system prompt for Gemini."""
    
    # Profile section — only include if we have real data
    if user_profile and any(user_profile.values()):
        profile_section = f"""
═══════════════════════════════════════════
YOU ARE TALKING TO THIS SPECIFIC USER:
═══════════════════════════════════════════
Name: {user_profile.get('name', 'User')}
Age Group: {user_profile.get('age_group', 'Unknown')}
Occupation: {user_profile.get('occupation', 'Unknown')}
Industry: {user_profile.get('industry', 'Unknown')}  
Income Level: {user_profile.get('income_level', 'Unknown')}
Investment Experience: {user_profile.get('investment_experience', 'Unknown')}
Risk Tolerance: {user_profile.get('risk_tolerance', 'Unknown')}
Financial Goals: {', '.join(user_profile.get('financial_goals', [])) or 'Not specified'}
Interests: {', '.join(user_profile.get('interests', [])) or 'Not specified'}
Life Stage: {user_profile.get('life_stage', 'Unknown')}
Investor Persona: {user_profile.get('primary_segment', 'Unknown')}

IMPORTANT: Use this profile to give PERSONALIZED answers. If they're a beginner, 
explain things simply. If experienced, be technical. Match your language to their profile."""
    else:
        profile_section = """
USER PROFILE: Not yet completed. Encourage them to complete their profile 
for personalized recommendations at /onboarding. In the meantime, ask 
clarifying questions to understand their needs."""

    # Page context section
    if page_context:
        context_section = f"""
CURRENT PAGE CONTEXT:
The user is currently reading/viewing: {page_context}
Answer questions in the context of what they are reading."""
    else:
        context_section = ""

    return f"""You are the ET AI Concierge — an intelligent, autonomous financial advisor powered by
Economic Times, India's #1 business media brand.

{profile_section}

{ET_SERVICES_CATALOGUE}

{context_section}

═══════════════════════════════════════════
HOW YOU MUST BEHAVE:
═══════════════════════════════════════════
1. ANSWER FIRST: Always directly and specifically answer the user's question.
   - If they ask about a stock: give real analysis (P/E, sector, outlook)
   - If they ask about a course: compare courses and recommend the BEST ONE for THEIR profile
   - If they ask about markets: give current market context
   - If they ask about tax: give specific actionable tax advice
   - NEVER give a generic "ET offers many products" type answer — that is FORBIDDEN.

2. CROSS-SELL NATURALLY: After answering, naturally suggest ONE highly relevant ET service.
   - The suggestion MUST be directly connected to what they just asked
   - Be specific with price, what they get, and WHY it fits THIS user's profile
   - Example: "Given you're a {user_profile.get('investment_experience', 'new')} investor 
     focused on {', '.join((user_profile.get('financial_goals') or ['growth'])[:1])}, 
     the ET Masterclass on [specific topic] would be perfect for you."
   - Sound like a knowledgeable friend, NOT a salesperson

3. REMEMBER CONTEXT: You have access to conversation history. Reference earlier messages naturally.

4. BE DYNAMIC: Every response should be different and tailored. NEVER repeat generic pitches.

5. FORMAT: Keep responses conversational, 2-4 paragraphs max. Use ₹ for rupees.

RESPOND IN THIS JSON FORMAT (your ENTIRE response must be valid JSON):
{{
  "answer": "Your direct, personalized answer to the user's question here",
  "cross_sell": {{
    "service": "Exact service name from the catalogue",
    "why_for_you": "1-2 sentences explaining why THIS service fits THIS user's specific profile and question",
    "price": "Exact price",
    "cta": "Compelling call to action button text",
    "url": "/et-prime OR /masterclass OR /portfolio"
  }}
}}"""


def _format_history(history: Optional[List[Dict[str, str]]]) -> str:
    if not history:
        return "No prior conversation."

    snippets = []
    for msg in history[-8:]:
        role = "User" if msg.get("role") == "user" else "Assistant"
        snippets.append(f"{role}: {msg.get('content', '')}")
    return "\n".join(snippets)


def _run_model_call(fn, timeout_seconds: int = 12):
    executor = ThreadPoolExecutor(max_workers=1)
    future = executor.submit(fn)
    try:
        result = future.result(timeout=timeout_seconds)
        executor.shutdown(wait=False, cancel_futures=False)
        return result
    except FuturesTimeoutError:
        logger.warning("Gemini call timed out after %ss", timeout_seconds)
        future.cancel()
        executor.shutdown(wait=False, cancel_futures=True)
        return None
    except Exception:
        executor.shutdown(wait=False, cancel_futures=True)
        raise


def _pick_course_for_profile(user_profile: Optional[Dict]) -> Dict[str, str]:
    profile = user_profile or {}
    experience = (profile.get("investment_experience") or "").lower()
    risk = (profile.get("risk_tolerance") or "").lower()
    age_group = (profile.get("age_group") or "").lower()
    goals = [str(goal).lower() for goal in (profile.get("financial_goals") or [])]

    if experience == "advanced" or risk == "aggressive":
        return {
            "service": "ET Masterclass: F&O Trading Strategies",
            "price": "₹2499",
            "url": "/masterclass",
            "cta": "See F&O Masterclass",
            "why_for_you": "You already show signs of higher risk appetite or experience, so an advanced derivatives course is the strongest fit.",
            "answer": "Based on your profile, the best ET course fit is ET Masterclass: F&O Trading Strategies. It suits investors who already understand the basics and want structured training in options, hedging, and strategy execution.",
        }

    if age_group in {"31-35", "36-40"} or "tax_saving" in goals or "retirement_planning" in goals:
        return {
            "service": "ET Masterclass: Personal Finance for the 30s",
            "price": "₹999",
            "url": "/masterclass",
            "cta": "See Personal Finance Course",
            "why_for_you": "Your profile suggests practical money decisions matter right now, so this course is the most immediately useful.",
            "answer": "Based on your profile, the strongest ET course match is ET Masterclass: Personal Finance for the 30s. It is the best fit when you need a practical mix of SIP planning, tax decisions, insurance, and long-term money structure rather than only stock-picking theory.",
        }

    return {
        "service": "ET Masterclass: Stock Market Mastery 2026",
        "price": "₹1499",
        "url": "/masterclass",
        "cta": "See Stock Market Mastery",
        "why_for_you": "It gives the clearest beginner-to-intermediate foundation for building confidence in stocks and portfolio basics.",
        "answer": "Based on your profile, the best ET course to start with is ET Masterclass: Stock Market Mastery 2026. It is the most balanced choice for building stock market basics, learning portfolio construction, and becoming more confident before moving into advanced trading topics.",
    }


def _get_next_ipo_summary() -> Optional[Dict[str, str]]:
    db = SessionLocal()
    try:
        ipo = (
            db.query(IPO)
            .filter(IPO.status.in_(["open", "upcoming"]))
            .order_by(IPO.open_date.asc())
            .first()
        )
        if not ipo:
            return None

        open_date = ipo.open_date.isoformat() if getattr(ipo, "open_date", None) else "date to be announced"
        price_band = None
        if ipo.price_band_low and ipo.price_band_high:
            price_band = f"₹{ipo.price_band_low}-₹{ipo.price_band_high}"

        return {
            "company_name": ipo.company_name,
            "open_date": open_date,
            "price_band": price_band or "price band awaited",
            "gmp": f"{float(ipo.gmp_percent):.0f}% GMP" if ipo.gmp_percent is not None else "GMP not available",
            "status": ipo.status,
        }
    except Exception as e:
        logger.warning("Unable to load upcoming IPO context: %s", e)
        return None
    finally:
        db.close()


def _local_agentic_fallback(
    message: str,
    user_profile: Optional[Dict] = None,
    page_context: Optional[str] = None,
) -> Dict[str, Any]:
    message_lower = (message or "").lower()
    profile = user_profile or {}
    name = profile.get("name") or "there"

    if any(term in message_lower for term in ["course", "masterclass", "learn"]):
        course = _pick_course_for_profile(profile)
        return {
            "answer": f"{course['answer']} {course['why_for_you']}",
            "cross_sell": {
                "service": course["service"],
                "why_for_you": course["why_for_you"],
                "price": course["price"],
                "cta": course["cta"],
                "url": course["url"],
            },
        }

    if "ipo" in message_lower:
        next_ipo = _get_next_ipo_summary()
        if next_ipo:
            return {
                "answer": (
                    f"The next IPO on my radar is {next_ipo['company_name']}, currently marked as {next_ipo['status']}. "
                    f"It is expected to open on {next_ipo['open_date']} with a price band of {next_ipo['price_band']}, "
                    f"and the latest signal I have is {next_ipo['gmp']}. If you want, I can also tell you whether it looks better for listing gains or for longer-term investing."
                ),
                "cross_sell": {
                    "service": "ET Markets IPO Tracker (in ET Prime)",
                    "why_for_you": "It gives you live IPO dates, GMP, subscription numbers, and expert views in one place.",
                    "price": "FREE with ET Prime",
                    "cta": "Track This IPO",
                    "url": "/ipo",
                },
            }
        return {
            "answer": "If you're interested in IPOs, ET Prime is the strongest fit because it gives you IPO analysis, ratings, and access to the ET Markets IPO Tracker. That combination helps you decide whether to subscribe, track GMP, and follow allotment updates in one place.",
            "cross_sell": {
                "service": "ET Markets IPO Tracker (in ET Prime)",
                "why_for_you": "It bundles the IPO workflow into one place with ratings, GMP tracking, and allotment visibility.",
                "price": "FREE with ET Prime",
                "cta": "Explore IPO Tracker",
                "url": "/et-prime",
            },
        }

    if any(term in message_lower for term in ["tax", "80c", "elss"]):
        return {
            "answer": "For tax-saving questions, the most useful ET offer is the ET Prime Tax Saving Bundle because it is focused on FY planning, 80C ideas, ELSS picks, and tax-harvesting strategy. It is the quickest route if your goal is practical action instead of generic theory.",
            "cross_sell": {
                "service": "ET Prime Tax Saving Bundle",
                "why_for_you": "It directly matches tax-planning intent and gives actionable FY-focused guidance.",
                "price": "₹299",
                "cta": "Open Tax Saving Bundle",
                "url": "/et-prime",
            },
        }

    if any(term in message_lower for term in ["portfolio", "stock", "stocks", "market", "sip", "mutual fund", "invest"]):
        return {
            "answer": "I can help with that. Based on your profile, the best next step is to pair your question with either practical market guidance or a course that upgrades your investing skill level. If you want, ask me one focused question on stocks, SIPs, tax planning, or the best ET product for your current stage, and I'll tailor the answer.",
            "cross_sell": {
                "service": "ET Prime",
                "why_for_you": "It is the broadest fit when you need regular analysis, ideas, and explainers across markets and investing.",
                "price": "₹99/month",
                "cta": "Try ET Prime",
                "url": "/et-prime",
            },
        }

    page_note = f" I can also help with what you're viewing now: {page_context}." if page_context else ""
    return {
        "answer": f"Hi {name}, I'm ready to help with investing, ET courses, IPOs, tax planning, and ET products.{page_note} Ask me something specific and I'll tailor it to your profile.",
        "cross_sell": {
            "service": "ET Prime",
            "why_for_you": "It is the most flexible starting point for personalized market and investing support.",
            "price": "₹99/month",
            "cta": "Explore ET Prime",
            "url": "/et-prime",
        },
    }


def generate_response_agentic(
    message: str,
    history: List[Dict[str, str]] = None,
    user_profile: Optional[Dict] = None,
    page_context: Optional[str] = None,
) -> Dict[str, Any]:
    """
    The main agentic response generator.
    Returns a dict with 'answer' (str) and 'cross_sell' (dict).
    """
    model = get_gemini_model()
    if not model:
        logger.warning("Gemini model unavailable. Using local agentic fallback.")
        return _local_agentic_fallback(message, user_profile, page_context)

    system_prompt = _build_system_prompt(user_profile, page_context)
    history_text = _format_history(history)

    try:
        full_prompt = (
            f"{system_prompt}\n\n"
            f"RECENT CONVERSATION:\n{history_text}\n\n"
            f"CURRENT USER MESSAGE:\n{message}\n\n"
            f"Respond ONLY with valid JSON."
        )
        response = _run_model_call(lambda: model.generate_content(full_prompt))
        if response is None:
            return _local_agentic_fallback(message, user_profile, page_context)
        
        raw = response.text.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip().rstrip("```").strip()
        
        result = json.loads(raw)
        return {
            "answer": result.get("answer", raw),
            "cross_sell": result.get("cross_sell"),
        }
    except json.JSONDecodeError:
        # LLM didn't return clean JSON — extract what we can
        try:
            answer = response.text.strip()
            return {"answer": answer, "cross_sell": None}
        except Exception:
            return _local_agentic_fallback(message, user_profile, page_context)
    except Exception as e:
        logger.error(f"Gemini agentic response failed: {e}", exc_info=True)
        return _local_agentic_fallback(message, user_profile, page_context)


# ── Legacy compatibility (Phase 1 path) ──────────────────────────────────────
def generate_response(
    message: str,
    history: List[Dict[str, str]] = None,
    user_profile: Optional[Dict] = None,
    page_context: Optional[str] = None,
) -> str:
    """Legacy wrapper — now injects profile into the agentic generator."""
    result = generate_response_agentic(message, history, user_profile, page_context)
    return result["answer"]


def classify_intent(message: str) -> str:
    """Classify the user intent into predefined buckets using Gemini."""
    message_lower = (message or "").lower()
    if "course" in message_lower or "masterclass" in message_lower:
        return "course_query"
    if "ipo" in message_lower:
        return "ipo_query"
    if "tax" in message_lower or "80c" in message_lower or "elss" in message_lower:
        return "tax_query"
    if "portfolio" in message_lower:
        return "portfolio_query"
    if "stock" in message_lower or "stocks" in message_lower or "market" in message_lower:
        return "stock_query"
    if "sip" in message_lower or "mutual fund" in message_lower:
        return "mutual_fund_query"

    model = get_gemini_model()
    if not model:
        return "general_question"
    try:
        prompt = (
            f"Classify this user message into EXACTLY ONE of these categories: "
            f"learning, investing, stock_query, ipo_query, tax_query, mutual_fund_query, "
            f"course_query, service_inquiry, portfolio_query, general_question. "
            f"Message: \"{message}\". "
            f"Reply with ONLY the category name, nothing else."
        )
        response = _run_model_call(lambda: model.generate_content(prompt), timeout_seconds=8)
        if response is None:
            return "general_question"
        intent = response.text.strip().lower().split()[0]
        valid = ["learning", "investing", "stock_query", "ipo_query", "tax_query",
                 "mutual_fund_query", "course_query", "service_inquiry", "portfolio_query", "general_question"]
        return intent if intent in valid else "general_question"
    except Exception:
        return "general_question"
